// Atividade/Aula 4/cardapio-angular/src/app/app.ts
import { Component, computed, effect, signal } from '@angular/core';
import { Cabecalho } from './components/cabecalho/cabecalho';
import { FiltroCategorias } from './components/filtro-categorias/filtro-categorias';
import { ProdutoCard } from './components/produto-card/produto-card';
import { CarrinhoResumo } from './components/carrinho-resumo/carrinho-resumo';
import { Rodape } from './components/rodape/rodape';
import { CATEGORIAS, ItemCarrinho, PRODUTOS, Produto } from './data/produtos';

@Component({
  selector: 'app-root',
  imports: [Cabecalho, FiltroCategorias, ProdutoCard, CarrinhoResumo, Rodape],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  protected readonly categorias = CATEGORIAS;

  // signal: estado reativo do componente
  protected readonly categoriaAtiva = signal('Todos');
  protected readonly itensCarrinho = signal<ItemCarrinho[]>([]);

  // computed: lista filtrada recalculada automaticamente
  protected readonly produtosFiltrados = computed(() =>
    this.categoriaAtiva() === 'Todos'
      ? PRODUTOS
      : PRODUTOS.filter((produto) => produto.categoria === this.categoriaAtiva()),
  );

  protected readonly quantidadeItens = computed(() =>
    this.itensCarrinho().reduce((soma, item) => soma + item.quantidade, 0),
  );

  constructor() {
    // effect: efeito colateral disparado quando o signal muda
    effect(() => {
      const quantidade = this.quantidadeItens();
      document.title = quantidade
        ? `Café Aroma (${quantidade})`
        : 'Café Aroma · Cardápio Digital';
    });
  }

  protected selecionarCategoria(categoria: string): void {
    this.categoriaAtiva.set(categoria);
  }

  protected adicionarProduto(produto: Produto): void {
    this.itensCarrinho.update((itens) => {
      const existente = itens.find((item) => item.produto.id === produto.id);

      if (existente) {
        return itens.map((item) =>
          item.produto.id === produto.id
            ? { ...item, quantidade: item.quantidade + 1 }
            : item,
        );
      }

      return [...itens, { produto, quantidade: 1 }];
    });
  }

  protected removerProduto(idProduto: number): void {
    this.itensCarrinho.update((itens) =>
      itens
        .map((item) =>
          item.produto.id === idProduto
            ? { ...item, quantidade: item.quantidade - 1 }
            : item,
        )
        .filter((item) => item.quantidade > 0),
    );
  }
}

// Atividade/Aula 2/cardapio-react/src/App.jsx
import { useEffect, useMemo, useState } from 'react'
import Cabecalho from './components/Cabecalho'
import FiltroCategorias from './components/FiltroCategorias'
import ProdutoCard from './components/ProdutoCard'
import Carrinho from './components/Carrinho'
import Rodape from './components/Rodape'
import { produtos, categorias } from './data/produtos'

function App() {
  // useState: estado do componente
  const [categoriaAtiva, setCategoriaAtiva] = useState('Todos')
  const [itensCarrinho, setItensCarrinho] = useState([])

  // useMemo: recalcula a lista filtrada apenas quando a categoria muda
  const produtosFiltrados = useMemo(() => {
    if (categoriaAtiva === 'Todos') return produtos
    return produtos.filter((produto) => produto.categoria === categoriaAtiva)
  }, [categoriaAtiva])

  const quantidadeItens = itensCarrinho.reduce(
    (soma, item) => soma + item.quantidade,
    0,
  )

  // useEffect: efeito colateral executado quando o carrinho muda
  useEffect(() => {
    document.title = quantidadeItens
      ? `Café Aroma (${quantidadeItens})`
      : 'Café Aroma · Cardápio Digital'
  }, [quantidadeItens])

  function adicionarProduto(produto) {
    setItensCarrinho((itens) => {
      const existente = itens.find((item) => item.produto.id === produto.id)
      if (existente) {
        return itens.map((item) =>
          item.produto.id === produto.id
            ? { ...item, quantidade: item.quantidade + 1 }
            : item,
        )
      }
      return [...itens, { produto, quantidade: 1 }]
    })
  }

  function removerProduto(idProduto) {
    setItensCarrinho((itens) =>
      itens
        .map((item) =>
          item.produto.id === idProduto
            ? { ...item, quantidade: item.quantidade - 1 }
            : item,
        )
        .filter((item) => item.quantidade > 0),
    )
  }

  return (
    <>
      <Cabecalho quantidadeItens={quantidadeItens} />

      <main className="container">
        <section className="hero">
          <h2>Sabor que combina com o seu dia</h2>
          <p>
            Cafés especiais, salgados quentinhos e doces artesanais. Monte seu
            pedido escolhendo os itens abaixo.
          </p>
        </section>

        <FiltroCategorias
          categorias={categorias}
          categoriaAtiva={categoriaAtiva}
          aoSelecionar={setCategoriaAtiva}
        />

        <Carrinho itens={itensCarrinho} aoRemover={removerProduto} />

        <div className="lista-produtos">
          {produtosFiltrados.map((produto) => (
            <ProdutoCard
              key={produto.id}
              produto={produto}
              aoAdicionar={adicionarProduto}
            />
          ))}
        </div>
      </main>

      <Rodape />
    </>
  )
}

export default App
