// Atividade/Aula 3/cardapio-vue/src/components/ProdutoCard.vue
<script setup lang="ts">
import type { Produto } from '../data/produtos'
import { formatarPreco } from '../utils/formatarPreco'

// Card reutilizável de produto
defineProps<{ produto: Produto }>()

const emit = defineEmits<{ (evento: 'adicionar', produto: Produto): void }>()
</script>

<template>
  <article class="card">
    <div class="card-emoji">{{ produto.emoji }}</div>
    <span class="tag-categoria">{{ produto.categoria }}</span>
    <h3>{{ produto.nome }}</h3>
    <p class="card-descricao">{{ produto.descricao }}</p>
    <div class="card-rodape">
      <span class="preco">{{ formatarPreco(produto.preco) }}</span>
      <button class="btn-adicionar" @click="emit('adicionar', produto)">
        Adicionar
      </button>
    </div>
  </article>
</template>

// Atividade/Aula 2/cardapio-react/src/components/ProdutoCard.jsx
import { formatarPreco } from '../utils/formatarPreco'

// Card reutilizável de produto
function ProdutoCard({ produto, aoAdicionar }) {
  return (
    <article className="card">
      <div className="card-emoji">{produto.emoji}</div>
      <span className="tag-categoria">{produto.categoria}</span>
      <h3>{produto.nome}</h3>
      <p className="card-descricao">{produto.descricao}</p>
      <div className="card-rodape">
        <span className="preco">{formatarPreco(produto.preco)}</span>
        <button className="btn-adicionar" onClick={() => aoAdicionar(produto)}>
          Adicionar
        </button>
      </div>
    </article>
  )
}

export default ProdutoCard
