// Atividade/Aula 2/cardapio-react/src/App.jsx
import { useEffect, useMemo, useState } from 'react'
import Cabecalho from './components/Cabecalho'
import FiltroCategorias from './components/FiltroCategorias'
import ProdutoCard from './components/ProdutoCard'
import Carrinho from './components/Carrinho'
import Rodape from './components/Rodape'
import { produtos, categorias } from './data/produtos'

function App() {
  // useState: estado do componente
  const [categoriaAtiva, setCategoriaAtiva] = useState('Todos')
  const [itensCarrinho, setItensCarrinho] = useState([])

  // useMemo: recalcula a lista filtrada apenas quando a categoria muda
  const produtosFiltrados = useMemo(() => {
    if (categoriaAtiva === 'Todos') return produtos
    return produtos.filter((produto) => produto.categoria === categoriaAtiva)
  }, [categoriaAtiva])

  const quantidadeItens = itensCarrinho.reduce(
    (soma, item) => soma + item.quantidade,
    0,
  )

  // useEffect: efeito colateral executado quando o carrinho muda
  useEffect(() => {
    document.title = quantidadeItens
      ? `Café Aroma (${quantidadeItens})`
      : 'Café Aroma · Cardápio Digital'
  }, [quantidadeItens])

  function adicionarProduto(produto) {
    setItensCarrinho((itens) => {
      const existente = itens.find((item) => item.produto.id === produto.id)
      if (existente) {
        return itens.map((item) =>
          item.produto.id === produto.id
            ? { ...item, quantidade: item.quantidade + 1 }
            : item,
        )
      }
      return [...itens, { produto, quantidade: 1 }]
    })
  }

  function removerProduto(idProduto) {
    setItensCarrinho((itens) =>
      itens
        .map((item) =>
          item.produto.id === idProduto
            ? { ...item, quantidade: item.quantidade - 1 }
            : item,
        )
        .filter((item) => item.quantidade > 0),
    )
  }

  return (
    <>
      <Cabecalho quantidadeItens={quantidadeItens} />

      <main className="container">
        <section className="hero">
          <h2>Sabor que combina com o seu dia</h2>
          <p>
            Cafés especiais, salgados quentinhos e doces artesanais. Monte seu
            pedido escolhendo os itens abaixo.
          </p>
        </section>

        <FiltroCategorias
          categorias={categorias}
          categoriaAtiva={categoriaAtiva}
          aoSelecionar={setCategoriaAtiva}
        />

        <Carrinho itens={itensCarrinho} aoRemover={removerProduto} />

        <div className="lista-produtos">
          {produtosFiltrados.map((produto) => (
            <ProdutoCard
              key={produto.id}
              produto={produto}
              aoAdicionar={adicionarProduto}
            />
          ))}
        </div>
      </main>

      <Rodape />
    </>
  )
}

export default App

// Atividade/Aula 3/cardapio-vue/src/App.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import AppCabecalho from './components/AppCabecalho.vue'
import FiltroCategorias from './components/FiltroCategorias.vue'
import ProdutoCard from './components/ProdutoCard.vue'
import CarrinhoResumo from './components/CarrinhoResumo.vue'
import AppRodape from './components/AppRodape.vue'
import { produtos, categorias, type ItemCarrinho, type Produto } from './data/produtos'

// ref: estado reativo
const categoriaAtiva = ref('Todos')
const itensCarrinho = ref<ItemCarrinho[]>([])

// computed: lista filtrada recalculada automaticamente
const produtosFiltrados = computed(() =>
  categoriaAtiva.value === 'Todos'
    ? produtos
    : produtos.filter((produto) => produto.categoria === categoriaAtiva.value),
)

const quantidadeItens = computed(() =>
  itensCarrinho.value.reduce((soma, item) => soma + item.quantidade, 0),
)

// watch: observa o estado e executa um efeito colateral
watch(quantidadeItens, (quantidade) => {
  document.title = quantidade
    ? `Café Aroma (${quantidade})`
    : 'Café Aroma · Cardápio Digital'
})

function adicionarProduto(produto: Produto) {
  const existente = itensCarrinho.value.find(
    (item) => item.produto.id === produto.id,
  )

  if (existente) {
    existente.quantidade++
  } else {
    itensCarrinho.value.push({ produto, quantidade: 1 })
  }
}

function removerProduto(idProduto: number) {
  const item = itensCarrinho.value.find((i) => i.produto.id === idProduto)
  if (!item) return

  item.quantidade--
  if (item.quantidade === 0) {
    itensCarrinho.value = itensCarrinho.value.filter(
      (i) => i.produto.id !== idProduto,
    )
  }
}
</script>

<template>
  <AppCabecalho :quantidade-itens="quantidadeItens" />

  <main class="container">
    <section class="hero">
      <h2>Sabor que combina com o seu dia</h2>
      <p>
        Cafés especiais, salgados quentinhos e doces artesanais. Monte seu
        pedido escolhendo os itens abaixo.
      </p>
    </section>

    <FiltroCategorias
      :categorias="categorias"
      :categoria-ativa="categoriaAtiva"
      @selecionar="categoriaAtiva = $event"
    />

    <CarrinhoResumo :itens="itensCarrinho" @remover="removerProduto" />

    <div class="lista-produtos">
      <ProdutoCard
        v-for="produto in produtosFiltrados"
        :key="produto.id"
        :produto="produto"
        @adicionar="adicionarProduto"
      />
    </div>
  </main>

  <AppRodape />
</template>
